export const today = "2026-11-16";
export const seed = {
  players: [
    "陳柏宇",
    "林冠廷",
    "王子豪",
    "張祐誠",
    "黃品睿",
    "李承恩",
    "吳俊傑",
    "劉宇翔",
  ].map((name, i) => ({
    id: `p${i + 1}`,
    name,
    birthDate: `2002-05-${String(i + 10).padStart(2, "0")}`,
    sex: "男",
    bodyFat: i === 0 ? 14 : null,
    sport: "籃球",
    weeklyTraining: 5,
    goal: ["維持", "增肌", "比賽準備"][i % 3],
    dietaryRestrictions: "無",
    allergies: i === 0 ? "花生" : "無",
    notes: "示範資料，請依實際情況更新",

    number: [7, 12, 23, 9, 11, 3, 15, 21][i],
    position: ["控球後衛", "小前鋒", "中鋒", "得分後衛", "大前鋒"][i % 5],
    team: "男子籃球隊",
    height: 178 + i * 3,
    weight: 72 + i * 3,
    target: { calories: 2800, protein: 150, carbs: 374.5, fat: 78 },
  })),
  foods: [
    {
      id: "f1",
      name: "香煎雞胸肉",
      category: "蛋白質",
      calories: 165,
      protein: 31,
      carbs: 0,
      fat: 3.6,
      emoji: "🍗",
    },
    {
      id: "f2",
      name: "糙米飯",
      category: "全穀雜糧",
      calories: 111,
      protein: 2.6,
      carbs: 23,
      fat: 0.9,
      emoji: "🍚",
    },
    {
      id: "f3",
      name: "清炒花椰菜",
      category: "蔬菜",
      calories: 45,
      protein: 3.7,
      carbs: 5,
      fat: 1.5,
      emoji: "🥦",
    },
    {
      id: "f4",
      name: "水煮蛋",
      category: "蛋白質",
      calories: 155,
      protein: 13,
      carbs: 1.1,
      fat: 11,
      emoji: "🥚",
    },
    {
      id: "f5",
      name: "烤鮭魚",
      category: "蛋白質",
      calories: 208,
      protein: 20,
      carbs: 0,
      fat: 13,
      emoji: "🐟",
    },
    {
      id: "f6",
      name: "烤地瓜",
      category: "全穀雜糧",
      calories: 115,
      protein: 1.3,
      carbs: 27,
      fat: 0.2,
      emoji: "🍠",
    },
  ],
  records: Array.from({ length: 8 }, (_, i) => ({
    id: `r${i}`,
    playerId: `p${i + 1}`,
    date: today,
    meal: "早餐",
    time: "08:15",
    items: [
      { foodId: "f4", grams: 100 },
      { foodId: "f6", grams: 200 },
    ],
    source: "手動記錄",
  })).concat(
    Array.from({ length: 6 }, (_, i) => ({
      id: `rl${i}`,
      playerId: `p${i + 1}`,
      date: today,
      meal: "午餐",
      time: `12:${10 + i * 3}`,
      items: [
        { foodId: "f1", grams: 180 },
        { foodId: "f2", grams: 250 },
        { foodId: "f3", grams: 150 },
      ],
      source: "人工確認",
    })),
  ),
};
